### ISSUE TITLE
Add decklist to overlay

### ISSUE THREAD

**Issue by beheh** [HearthSim/twitch-hdt-frontend#9]

**Comment by jleclanche** [comment]
Not necessarily v1 but having the native HDT decklist be hoverable would be a huge feature. It's unfortunate that we can't have it up all the time but we can link a wiki page on how to set that up or something in the config...

**Comment by beheh** [comment]
Done, but needs hovering and scaling.

**Comment by beheh** [comment]
Done, still needs animations.
